---
title: "Demographics Across Countries"
format: 
  html:
    output-file: "index.html"

---

(We're going to redo a bit of Assignment 2)

```{r}
#| echo: false
#| warning: false
library(dplyr)
library(tidyr)
library(reactable)
```

The `countries` dataset can be displayed with an interactive data table:

```{r}
df <- read.csv("http://manctsui.github.io/datasets/countries.csv")
reactable(df, defaultPageSize = 4, searchable = TRUE)
```

# Net migration

Net migration is given by the formula:
$$
\text{Migration into country} - \text{Migration out of country} 
$$

Which countries have the msot negative vs most positive migration?

:::{#fig-countries-migration}
```{r}
#| code-fold: true
#| layout-ncol: 2

least <- df |>
  arrange(Net.migration) |>
  head(3) |>
  select("Most Negative Net Migration" = Country)

reactable(least)

most <- df |>
  arrange(desc(Net.migration)) |>
  head(3) |>
  select("Most Positive Net Migration" = Country)

reactable(most)

```
Countries with most extreme net migrations
:::

